version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=vkr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow
    volumes:
      - './db:/docker-entrypoint-initdb.d/'

  flask:
    #restart: always
    build: ./flask_app/
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/usr/src/app
    depends_on:
      - "postgres"
